<CODEGEN_FILENAME><Structure_name>_Data.CodeGen.dbc</CODEGEN_FILENAME>
<OPTIONAL_USERTOKEN>RPSDATAFILES= </OPTIONAL_USERTOKEN>
;//****************************************************************************
;//
;// Title:       Symphony_Data.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to define structure based Data Object
;//
;// Author:      Richard C. Morris, RCP Consultants.
;//
;// Copyright (c) 2019, RCP Consultants, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;//****************************************************************************
;;****************************************************************************
;; WARNING: This code was generated by CodeGen. Any changes that you
;;          make to this code will be overwritten if the code is regenerated!
;;
;; Template author: Richard C. Morris, RCP Consultants.
;;
;; Template Name:   Symphony Framework : <TEMPLATE>.tpl
;;
;;***************************************************************************
import System
import System.Collections.Generic
import System.Text

import Symphony.Conductor.Model
import Symphony.Conductor.Converters

namespace <NAMESPACE>

    ;;define a structure that we can use around the applicaiton

	structure STR<Structure_name>
		.include '<structure_noalias>' repository <RPSDATAFILES>, norecord
	endstructure

    public partial class <Structure_name>_Data extends Symphony.Conductor.Model.DataObjectBase

		public const RPSStructureName	,String	,"<STRUCTURE_NOALIAS>"
		public const RPSStructureSize	,Int32	,<STRUCTURE_SIZE>

		private <structure_name>_main	,STR<Structure_name>
		private <structure_name>_store	,STR<Structure_name>

		private mDoneSynergyRecordValue	,boolean

		;;use symphony converters
		private mDateConveter		,@SynergyDecimalDateConverter	,new SynergyDecimalDateConverter()
		private mAlphaConveter		,@SynergyAlphaConverter	,new SynergyAlphaConverter()
		private mAlphaTFConverter	,@SynergyAlphaYNConverter	,new SynergyAlphaYNConverter()
		private mDecimalConverter	,@SynergyDecimalConverter	,new SynergyDecimalConverter()
		private mImpliedDecimalConveter	,@SynergyImpliedDecimalConverter	,new SynergyImpliedDecimalConverter()
		private mIntegerConveter	,@SynergyIntConverter	,new SynergyIntConverter()
		private mDecimalTFConverter	,@SynergyDecimalTFConverter	,new SynergyDecimalTFConverter()

		static method <Structure_name>_Data
			endparams
		proc
			mStaticFieldList = new List<BaseFieldInformation>()
			mStaticFieldDictionary = new Dictionary<string, int>()
			mStaticFieldNameList = new List<String>()
			mStaticFieldHeadingList = new List<String>()

			<SYMPHONY_LOOPSTART>
			<FIELD_LOOP>
			<IF LANGUAGE>
			<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			<SYMPHONY_LOOPINCREMENT>
			<IF NUMERIC>
			staticSetFieldInfo(mStaticFieldList, mStaticFieldDictionary, "<FIELD_SQLNAME>", "<Field_sqlname>",  "<FIELD_CHANGEM>", "<FIELD_ARRIVEM>",
			&	"<FIELD_LEAVEM>", "<FIELD_ORIGINAL_NAME>", <FIELD_POSITION>, <FIELD_SIZE>,
			&	<FIELD_ELEMENT0>, 0, 0, 0,
			&	"<FIELD_TYPE_NAME>", <IF REQUIRED>true</IF><IF OPTIONAL>false</IF>, <FIELD_MINVALUE>, <FIELD_MAXVALUE>)
			<ELSE>
			staticSetFieldInfo(mStaticFieldList, mStaticFieldDictionary, "<FIELD_SQLNAME>", "<Field_sqlname>",  "<FIELD_CHANGEM>", "<FIELD_ARRIVEM>",
			&	"<FIELD_LEAVEM>", "<FIELD_ORIGINAL_NAME>", <FIELD_POSITION>, <FIELD_SIZE>,
			&	<FIELD_ELEMENT0>, 0, 0, 0,
			&	"<FIELD_TYPE_NAME>", <IF REQUIRED>true</IF><IF OPTIONAL>false</IF>, 0, 0)
			</IF NUMERIC>
			</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			</IF LANGUAGE>
			</FIELD_LOOP>

			<FIELD_LOOP>
			<IF LANGUAGE>
			<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			mStaticFieldNameList.Add("<Field_sqlname>")
			mStaticFieldHeadingList.Add("<FIELD_HEADING>")
			</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			</IF LANGUAGE>
			</FIELD_LOOP>

			mreturn
		endmethod

        ;;; <summary>
        ;;;  Constructor, initialise the base fields
        ;;; </summary>
        public method <Structure_name>_Data
            endparams
            parent()
        proc
			mDoneSynergyRecordValue = true
			doingClearFocus = false

			configureFieldInfo()
			setFieldNames()
			InitData()
			mDoneSynergyRecordValue = false
			extendedConstructor()
        endmethod

        ;;; <summary>
        ;;; Alternate constructor, accepts the inital value to assign to the object
        ;;; </summary>
        ;;; <param name="synRec">Provide the data to load into the _DATAOBJECT_</param>
        public method <Structure_name>_Data
            in req synRec       ,String
            endparams
            parent()
        proc
			mDoneSynergyRecordValue = true
			doingClearFocus = false

			mIsNew = false
			configureFieldInfo()
			setFieldNames()
			<structure_name>_main = synRec
			;OriginalSynergyRecord = synRec
			extendedConstructor()
        endmethod

		;;; <summary>
		;;; Alternate constructor, accepts the inital value to assign to the object
		;;; </summary>
		;;; <param name="synRec">Provide the data to load into the _DATAOBJECT_</param>
		public method <Structure_name>_Data
			in req synRec       ,STR<Structure_name>
			endparams
			parent()
		proc
			mDoneSynergyRecordValue = true
			doingClearFocus = false

			mIsNew = false
			configureFieldInfo()
			setFieldNames()
			<structure_name>_main = synRec
			;OriginalSynergyRecord = synRec
			extendedConstructor()
		endmethod

		;;; <summary>
		;;; Alternate constructor, accepts the inital value to assign to the object.
		;;; Also accepts the boolean value to assign to the ObjectRaisesPropertyChanged property.
		;;; </summary>
		;;; <param name="synRec">Provide the data to load into the _DATAOBJECT_</param>
		;;; <param name="notifyUI">values passed onto the ObjectRaisesPropertyChanged property.</param>
		public method <Structure_name>_Data
			in req synRec       ,String
			in req notifyUI		,DataObjectNotificationState
			endparams
			parent()
		proc
			mDoneSynergyRecordValue = true
			doingClearFocus = false

			ObjectRaisesPropertyChanged = notifyUI
			mIsNew = false
			configureFieldInfo()
			setFieldNames()
			<structure_name>_main = synRec
			;OriginalSynergyRecord = synRec
			extendedConstructor()
		endmethod

		;;; <summary>
		;;; Alternate constructor, accepts the inital value to assign to the object.
		;;; Also accepts the boolean value to assign to the ObjectRaisesPropertyChanged property.
		;;; </summary>
		;;; <param name="synRec">Provide the data to load into the _DATAOBJECT_</param>
		;;; <param name="notifyUI">values passed onto the ObjectRaisesPropertyChanged property.</param>
		public method <Structure_name>_Data
			in req synRec       ,STR<Structure_name>
			in req notifyUI		,DataObjectNotificationState
			endparams
			parent()
		proc
			mDoneSynergyRecordValue = true
			doingClearFocus = false

			ObjectRaisesPropertyChanged = notifyUI
			mIsNew = false
			configureFieldInfo()
			setFieldNames()
			<structure_name>_main = synRec
;			OriginalSynergyRecord = synRec
			extendedConstructor()
		endmethod

        ;;Set up the arrays of field details
        private method configureFieldInfo	,void
			endparams
		proc
			
			mfieldArray = mStaticFieldList
			mfieldDictionary = mStaticFieldDictionary

		endmethod

		private static mStaticFieldList			,@List<BaseFieldInformation>
		private static mStaticFieldDictionary	,@Dictionary<string, int>
		private static mStaticFieldNameList		,@List<String>
		private static mStaticFieldHeadingList	,@List<String>

        ;;Set up the arrays of field names and headings
        private method setFieldNames	,void
			endparams
		proc

			mFieldNames = mStaticFieldNameList
			mFieldHeadings = mStaticFieldHeadingList
			
		endmethod

        ;;Expose fields as properties for data binding
<SYMPHONY_LOOPSTART>
<FIELD_LOOP>
<IF LANGUAGE>
<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
        ;;<Field_name>
<IF ALPHA>
<IF CHECKBOX>
		public property <Field_sqlname>, Boolean
</IF CHECKBOX>
<IF NOCHECKBOX>
		public property <Field_sqlname>, String
</IF NOCHECKBOX>
</IF ALPHA>
<IF USER>
<IF CHECKBOX>
		public property <Field_sqlname>, Boolean
</IF CHECKBOX>
<IF NOCHECKBOX>
		public property <Field_sqlname>, String
</IF NOCHECKBOX>
</IF USER>
<IF DECIMAL>
<IF PRECISION>
		public property <Field_sqlname>, Decimal
</IF PRECISION>
<IF NOPRECISION>
<IF COERCEBOOLEAN>
		public property <Field_sqlname>, Boolean
</IF COERCEBOOLEAN>
<IF NOCOERCEBOOLEAN>
<IF CHECKBOX>
		public property <Field_sqlname>, Boolean
</IF CHECKBOX>
<IF NOCHECKBOX>
		public property <Field_sqlname>, Int32
</IF NOCHECKBOX>
</IF NOCOERCEBOOLEAN>
</IF NOPRECISION>
</IF DECIMAL>
<IF I1>
		public property <Field_sqlname>, Byte
</IF I1>
<IF I2>
		public property <Field_sqlname>, Int16
</IF I2>
<IF I4>
		public property <Field_sqlname>, Int32
</IF I4>
<IF I8>
		public property <Field_sqlname>, Int64
</IF I8>
<IF AUTO_TIMESTAMP>
		public property <Field_sqlname>, DateTime?
</IF AUTO_TIMESTAMP>
<IF DATEORTIME>
<IF DATE_YYYYMMDD>
		public property <Field_sqlname>, DateTime?
</IF DATE_YYYYMMDD>
<IF DATE_YYMMDD>
		public property <Field_sqlname>, DateTime?
</IF DATE_YYMMDD>
<IF DATE_YYJJJ>
		public property <Field_sqlname>, DateTime?
</IF DATE_YYJJJ>
<IF TIME_HHMM>
		public property <Field_sqlname>, DateTime?
</IF TIME_HHMM>
<IF TIME_HHMMSS>
		public property <Field_sqlname>, DateTime?
</IF TIME_HHMMSS>
</IF DATEORTIME>
<IF BOOLEAN>
		public property <Field_sqlname>, Boolean
</IF BOOLEAN>
			method get
			proc
<IF ALPHA>
<IF CHECKBOX>
				mreturn (boolean)mAlphaTFConverter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF CHECKBOX>
<IF NOCHECKBOX>
				mreturn (string)mAlphaConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF NOCHECKBOX>
</IF ALPHA>
<IF USER>
<IF CHECKBOX>
				mreturn (boolean)mAlphaTFConverter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF CHECKBOX>
<IF NOCHECKBOX>
				mreturn (string)mAlphaConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF NOCHECKBOX>
</IF USER>
<IF DECIMAL>
<IF PRECISION>
				mreturn (decimal)mImpliedDecimalConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF PRECISION>
<IF NOPRECISION>
<IF COERCEBOOLEAN>
				mreturn (boolean)mDecimalTFConverter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF COERCEBOOLEAN>
<IF NOCOERCEBOOLEAN>
<IF CHECKBOX>
				mreturn (boolean)mDecimalTFConverter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF CHECKBOX>
<IF NOCHECKBOX>
				mreturn (int32)mIntegerConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF NOCHECKBOX>
</IF NOCOERCEBOOLEAN>
</IF NOPRECISION>
</IF DECIMAL>
<IF I1>
				mreturn (Byte)mIntegerConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF I1>
<IF I2>
				mreturn (int16)mIntegerConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF I2>
<IF I4>
				mreturn (int32)mIntegerConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF I4>
<IF I8>
				mreturn (int64)mIntegerConveter.Convert(<structure_name>_main.<field_name>, ^null, ^null, ^null)
</IF I8>
<IF AUTO_TIMESTAMP>
                data syndate	,a20	,%datetime_from_i8(<structure_name>_main.<field_name>)
                mreturn new DateTime(%integer(syndate(1:4)),%integer(syndate(5:2)),%integer(syndate(7:2)),%integer(syndate(9:2)),%integer(syndate(11:2)),%integer(syndate(13:2)))
</IF AUTO_TIMESTAMP>
<IF DATEORTIME>
<IF DATE_YYYYMMDD>
				mreturn (datetime?)mDateConveter.Convert(<structure_name>_main.<field_name>, ^null, "FORMAT:YYYYMMDD<IF NOTDATETODAY>|NODEFAULTODAY</IF>", ^null)
</IF DATE_YYYYMMDD>
<IF DATE_YYMMDD>
				mreturn (datetime?)mDateConveter.Convert(<structure_name>_main.<field_name>, ^null, "FORMAT:YYMMDD<IF NOTDATETODAY>|NODEFAULTODAY</IF>", ^null)
</IF DATE_YYMMDD>
<IF DATE_YYJJJ>
				mreturn (datetime?)mDateConveter.Convert(<structure_name>_main.<field_name>, ^null, "FORMAT:JULIAN<IF NOTDATETODAY>|NODEFAULTODAY</IF>", ^null)
</IF DATE_YYJJJ>
<IF TIME_HHMM>
				mreturn new Datetime(1, 1, 1, (int)<structure_name>_main.<field_name>(1:2), (int)<structure_name>_main.<field_name>(3:2), 0)
</IF TIME_HHMM>
<IF TIME_HHMMSS>
				mreturn new Datetime(1, 1, 1, (int)<structure_name>_main.<field_name>(1:2), (int)<structure_name>_main.<field_name>(3:2), <structure_name>_main.<field_name>(5:2))
</IF TIME_HHMMSS>
</IF DATEORTIME>
<IF BOOLEAN>
				mreturn <structure_name>_main.<field_name>
</IF BOOLEAN>
			endmethod
<IF AUTO_TIMESTAMP>
<ELSE>
			method set
			proc
</IF AUTO_TIMESTAMP>
<IF ALPHA>
<IF CHECKBOX>
				if (<Structure_name>_main.<field_name> .nes. (a)mAlphaTFConverter.ConvertBack(value, ^null, ^null, ^null))
</IF CHECKBOX>
<IF NOCHECKBOX>
				if (<Structure_name>_main.<field_name> .nes. (a)mAlphaConveter.ConvertBack(value, ^null, ^null, ^null))
</IF CHECKBOX>
</IF ALPHA>
<IF USER>
<IF CHECKBOX>
				if (<Structure_name>_main.<field_name> .nes. (a)mAlphaTFConverter.ConvertBack(value, ^null, ^null, ^null))
</IF CHECKBOX>
<IF NOCHECKBOX>
				if (<Structure_name>_main.<field_name> .nes. (a)mAlphaConveter.ConvertBack(value, ^null, ^null, ^null))
</IF NOCHECKBOX>
</IF USER>
<IF DECIMAL>
<IF PRECISION>
				if (<Structure_name>_main.<field_name> .ne. (id)mImpliedDecimalConveter.ConvertBack(value, ^null, ^null, ^null))
</IF PRECISION>
<IF NOPRECISION>
<IF COERCEBOOLEAN>
				if (<Structure_name>_main.<field_name> .ne. (d)mDecimalTFConverter.ConvertBack(value, ^null, ^null, ^null))
</IF COERCEBOOLEAN>
<IF NOCOERCEBOOLEAN>
<IF CHECKBOX>
				if (<Structure_name>_main.<field_name> .ne. (d)mDecimalTFConverter.ConvertBack(value, ^null, ^null, ^null))
</IF CHECKBOX>
<IF NOCHECKBOX>
				if (<Structure_name>_main.<field_name> .ne. (d)((i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null)))
</IF NOCHECKBOX>
</IF NOCOERCEBOOLEAN>
</IF NOPRECISION>
</IF DECIMAL>
<IF I1>
				if (<Structure_name>_main.<field_name> .ne. (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null))
</IF I1>
<IF I2>
				if (<Structure_name>_main.<field_name> .ne. (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null))
</IF I2>
<IF I4>
				if (<Structure_name>_main.<field_name> .ne. (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null))
</IF I4>
<IF I8>
				if (<Structure_name>_main.<field_name> .ne. (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null))
</IF I8>
<IF DATEORTIME>
<IF DATE_YYYYMMDD>
				if (<Structure_name>_main.<field_name> .ne. (d)mDateConveter.ConvertBack(value, ^null, ^null, ^null))
</IF DATE_YYYYMMDD>
<IF TIME_HHMM>
				data tempDateTime ,@DateTime  ,(DateTime)value
				data tempTime ,d4
				temptime(1:2) = tempDateTime.Hour
				temptime(3:2) = tempDateTime.Minute
				if (<Structure_name>_main.<field_name> .ne. tempTime)
</IF TIME_HHMM>
<IF TIME_HHMMSS>
				data tempDateTime ,@DateTime  ,(DateTime)value
				data tempTime ,d6
				temptime(1:2) = tempDateTime.Hour
				temptime(3:2) = tempDateTime.Minute
				temptime(5:2) = tempDateTime.Second
				if (<Structure_name>_main.<field_name> .ne. tempTime)
</IF TIME_HHMMSS>
</IF DATEORTIME>
<IF BOOLEAN>
				if (<Structure_name>_main.<field_name> .ne. value)
</IF BOOLEAN>
<IF AUTO_TIMESTAMP>
<ELSE>
				begin
</IF AUTO_TIMESTAMP>
<SYMPHONY_LOOPINCREMENT>;//increment the loop
<IF ALPHA>
<IF CHECKBOX>
					<Structure_name>_main.<field_name> = (a)mAlphaTFConverter.ConvertBack(value, ^null, ^null, ^null)
</IF CHECKBOX>
<IF NOCHECKBOX>
					<Structure_name>_main.<field_name> = (a)mAlphaConveter.ConvertBack(value, ^null, ^null, ^null)
</IF NOCHECKBOX>
</IF ALPHA>
<IF USER>
<IF CHECKBOX>
					<Structure_name>_main.<field_name> = (a)mAlphaTFConverter.ConvertBack(value, ^null, ^null, ^null)
</IF CHECKBOX>
<IF NOCHECKBOX>
					<Structure_name>_main.<field_name> = (a)mAlphaConveter.ConvertBack(value, ^null, ^null, ^null)
</IF NOCHECKBOX>
</IF USER>
<IF DECIMAL>
<IF PRECISION>
				    <Structure_name>_main.<field_name> = (id)mImpliedDecimalConveter.ConvertBack(value, ^null, ^null, ^null)
</IF PRECISION>
<IF NOPRECISION>
<IF COERCEBOOLEAN>
					<Structure_name>_main.<field_name> = (d)mDecimalTFConverter.ConvertBack(value, ^null, ^null, ^null)
</IF COERCEBOOLEAN>
<IF NOCOERCEBOOLEAN>
<IF CHECKBOX>
					<Structure_name>_main.<field_name> = (d)mDecimalTFConverter.ConvertBack(value, ^null, ^null, ^null)
</IF CHECKBOX>
<IF NOCHECKBOX>
					<Structure_name>_main.<field_name> = (d)((i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null))
</IF NOCHECKBOX>
</IF NOCOERCEBOOLEAN>
</IF NOPRECISION>
</IF DECIMAL>
<IF I1>
					<Structure_name>_main.<field_name> = (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null)
</IF I1>
<IF I2>
					<Structure_name>_main.<field_name> = (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null)
</IF I2>
<IF I4>
					<Structure_name>_main.<field_name> = (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null)
</IF I4>
<IF I8>
					<Structure_name>_main.<field_name> = (i)mIntegerConveter.ConvertBack(value, ^null, ^null, ^null)
</IF I8>
<IF DATEORTIME>
<IF DATE_YYYYMMDD>
					<Structure_name>_main.<field_name> = (d)mDateConveter.ConvertBack(value, ^null, ^null, ^null)
</IF DATE_YYYYMMDD>
<IF TIME_HHMM>
					<Structure_name>_main.<field_name> = tempTime
</IF TIME_HHMM>
<IF TIME_HHMMSS>
					<Structure_name>_main.<field_name> = tempTime
</IF TIME_HHMMSS>
</IF DATEORTIME>
<IF BOOLEAN>
					<Structure_name>_main.<field_name> = value
</IF BOOLEAN>
<IF AUTO_TIMESTAMP>
<ELSE>
					ValidateEnteredData(<SYMPHONY_LOOPVALUE>)
					RaisePropertyChanged("<Field_sqlname>")
</IF AUTO_TIMESTAMP>
<IF ALPHA>
<IF ARRAY>
					RaisePropertyChanged("<Field_basename>")
</IF ARRAY>
</IF ALPHA>
<IF AUTO_TIMESTAMP>
		endproperty
<ELSE>
				end
			endmethod
		endproperty
</IF AUTO_TIMESTAMP>
</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
</IF LANGUAGE>
</FIELD_LOOP>
			
        ;;; <summary>
        ;;; Expose the complete synergy record
        ;;; </summary>
		public override property SynergyRecord, String
            method get
            proc
                mreturn (String)<Structure_name>_main
            endmethod
            method set
            proc
				if (!mDoneSynergyRecordValue)
					OriginalSynergyRecord = value

				mDoneSynergyRecordValue = true
				
				setUsed()
                <Structure_name>_main = value

                ;;Signal that all fields have changed
                <SYMPHONY_LOOPSTART>
                <FIELD_LOOP>
				<IF LANGUAGE>
				<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
                if (<Structure_name>_store.<field_name> != <Structure_name>_main.<field_name>)
                begin
                    SetFieldValid("<Field_sqlname>")
				<SYMPHONY_LOOPINCREMENT>	;//increment the loop
                    if (mValidateSynergyData) ValidateEnteredData(<SYMPHONY_LOOPVALUE>)
                end
				</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
                </IF LANGUAGE>
                </FIELD_LOOP>
				RaisePropertyChanged(^null)
				RaiseSynergyRecordChanged()
				
				<Structure_name>_store = <Structure_name>_main
				
            endmethod
        endproperty

        ;;; <summary>
        ;;; Allow the host to initialise all fields.
        ;;; </summary>
        public override method InitData ,void
        proc
			init <Structure_name>_main
			RaisePropertyChanged(^null)
			parent.InitData()
        endmethod

        ;;; <summary>
        ;;; Allow the host to validate all fields. Each field will fire the validation method.
        ;;; </summary>
        public override method InitialValidateData, void
            endparams
        proc
			<SYMPHONY_LOOPSTART>
            <FIELD_LOOP>
			<IF LANGUAGE>
			<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			<SYMPHONY_LOOPINCREMENT>	;//increment the loop
            ValidateEnteredData(<SYMPHONY_LOOPVALUE>)
            RaisePropertyChanged("<Field_sqlname>")
			</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			</IF LANGUAGE>
            </FIELD_LOOP>

        endmethod

        ;;; <summary>
        ;;; Indicate from the UI which field now has focus. This then signals the
        ;;; CurrentFieldInfo change event so the UI can get the current field details
        ;;; </summary>
        ;;; <param name="fieldName">Name of field with focus</param>
        public override method SetFieldFocusFlag    ,void
            in req fieldName                        ,String
            endparams
        proc
            using fieldName select
			<SYMPHONY_LOOPSTART>
            <FIELD_LOOP>
			<IF LANGUAGE>
			<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			<SYMPHONY_LOOPINCREMENT>
            ("<FIELD_ORIGINAL_NAME>"), mCurrentField = <SYMPHONY_LOOPVALUE>
			</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			</IF LANGUAGE>
            </FIELD_LOOP>
            (),
                mCurrentField = 0
            endusing
            RaisePropertyChanged("CurrentFieldInfo")
        endmethod

        ;;; <summary>
        ;;; Expose information about the current field
        ;;; </summary>
        ;;; <returns>Current field information</returns>
        public property CurrentFieldInfo    ,String
            method get
            proc
                using mCurrentField select
				<SYMPHONY_LOOPSTART>
                <FIELD_LOOP>
				<IF LANGUAGE>
				<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
				<SYMPHONY_LOOPINCREMENT>
                (<SYMPHONY_LOOPVALUE>),    mreturn "<FIELD_INFOLINE>"
				</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
				</IF LANGUAGE>
                </FIELD_LOOP>
				(), mreturn ""  ;;if incorrect field value or not configured, ensure we clear the return value
                endusing
            endmethod
        endproperty

        ;;Expose properties to indicate whether fields are enabled
        <SYMPHONY_LOOPSTART>
        <FIELD_LOOP>
		<IF LANGUAGE>
		<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
		<SYMPHONY_LOOPINCREMENT>

        public property <Field_sqlname>IsEnabled, Boolean
            method get
            proc
                mreturn GetFieldEnabledState(<SYMPHONY_LOOPVALUE>)
            endmethod
            method set
            proc
                SetFieldEnabledState(<SYMPHONY_LOOPVALUE>, value)
                RaiseNonRPSPropertyChanged("<Field_sqlname>IsEnabled")
            endmethod
        endproperty
		</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
		</IF LANGUAGE>
        </FIELD_LOOP>

        ;;Expose properties to indicate whether fields are focussed
        <FIELD_LOOP>
		<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
		<IF LANGUAGE>
		private m<Field_sqlname>IsFocused	,Boolean
		public property <Field_sqlname>IsFocused, Boolean
			method get
			proc
				mreturn m<Field_sqlname>IsFocused
			endmethod
			method set
			proc
				clearFocus()
				m<Field_sqlname>IsFocused = value
				RaiseNonRPSPropertyChanged("<Field_sqlname>IsFocused")
			endmethod
		endproperty
		</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
		</IF LANGUAGE>
        </FIELD_LOOP>

        ;;Expose properties to indicate whether fields are read only
		<SYMPHONY_LOOPSTART>
		<FIELD_LOOP>
		<IF LANGUAGE>
		<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
		<SYMPHONY_LOOPINCREMENT>

		public property <Field_sqlname>IsReadOnly, Boolean
			method get
			proc
				mreturn GetFieldReadOnlyState(<SYMPHONY_LOOPVALUE>)
			endmethod
			method set
			proc
				SetFieldReadOnlyState(<SYMPHONY_LOOPVALUE>, value)
				RaiseNonRPSPropertyChanged("<Field_sqlname>IsReadOnly")
			endmethod
		endproperty
		</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
		</IF LANGUAGE>
        </FIELD_LOOP>

		private doingClearFocus	,Boolean

		private method clearFocus, void
			endparams
		proc
			if (!doingClearFocus)
			begin
				doingClearFocus = true
				<FIELD_LOOP>
				<IF LANGUAGE>
				<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
				if (<Field_sqlname>IsFocused) <Field_sqlname>IsFocused = false
				</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
				</IF LANGUAGE>
                </FIELD_LOOP>
				doingClearFocus = false
			end
		endmethod

		public method FieldErrorDetails	,void
			in req fldName				,String
			in req errorText			,String
			endparams
		proc
			setErrorDetails(fldName, errorText)
			RaisePropertyChanged(fldName)
		endmethod

		public method FieldValidDetails	,void
			in req fldName				,String
			endparams
		proc
			SetFieldValid(fldName)
			RaisePropertyChanged(fldName)
		endmethod

		public override method CompareObjects	,int
			in req obj1							,@Object
			in req obj2							,@Object
			in req colName						,String
			in req sortDir						,Symphony.Conductor.Framework.SynergySortOrder
			endparams

			record
				result		,int
			endrecord
		proc
			using colName select
			<FIELD_LOOP>
			<IF LANGUAGE>
			<IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			("<Field_sqlname>"),
			begin
				if (((<Structure_name>_Data)obj1).<Field_sqlname> == ((<Structure_name>_Data)obj2).<Field_sqlname>) then
					result = 0
				else
				begin
					if (((<Structure_name>_Data)obj1).<Field_sqlname> > ((<Structure_name>_Data)obj2).<Field_sqlname>) then
					begin
						if (sortDir == Symphony.Conductor.Framework.SynergySortOrder.Ascending) then
							result = -1
						else
							result = 1
					end
					else
					begin
						if (sortDir == Symphony.Conductor.Framework.SynergySortOrder.Descending) then
							result = -1
						else
							result = 1
					end
				end
			end
			</IF CUSTOM_NOT_SYMPHONY_ARRAY_FIELD>
			</IF LANGUAGE>
            </FIELD_LOOP>
			(),
				result = this.CustomCompareObjects(obj1, obj2, colName, sortDir)
			endusing

			mreturn result
		endmethod

	endclass
endnamespace

