<CODEGEN_FILENAME><Structure_name>_Data_fromXFSP.CodeGen.dbc</CODEGEN_FILENAME>
<REQUIRES_USERTOKEN>MODELNAMESPACE</REQUIRES_USERTOKEN>
<REQUIRES_USERTOKEN>CLIENTNAMESPACE</REQUIRES_USERTOKEN>
;//****************************************************************************
;//
;// Title:       Symphony_Data_fromXFSP.tpl
;//
;// Type:        CodeGen Template
;//
;// Description: Template to map data from an xfServerPlus class to a Symphony Data Object
;//
;// Author:      Richard C. Morris, Synergex Technology Evangelist
;//
;// Copyright (c) 2017, Synergex International, Inc. All rights reserved.
;//
;// Redistribution and use in source and binary forms, with or without
;// modification, are permitted provided that the following conditions are met:
;//
;// * Redistributions of source code must retain the above copyright notice,
;//   this list of conditions and the following disclaimer.
;//
;// * Redistributions in binary form must reproduce the above copyright notice,
;//   this list of conditions and the following disclaimer in the documentation
;//   and/or other materials provided with the distribution.
;//
;// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
;// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;// POSSIBILITY OF SUCH DAMAGE.
;//
;//****************************************************************************
;;****************************************************************************
;; WARNING: This code was generated by CodeGen. Any changes that you
;;          make to this code will be overwritten if the code is regenerated!
;;
;; Template author: Richard C. Morris, Synergex Technology Evangelist
;;
;; Template Name:   Symphony Framework : <TEMPLATE>.tpl
;;
;;***************************************************************************

import <CLIENTNAMESPACE>
import <MODELNAMESPACE>

namespace <NAMESPACE>

	public static class <Structure_name>_Data_fromXFSP
		
		;;; <summary>
		;;; Move data from the returned xfServerPlus data class to Symphony data object based class
		;;; </summary>
		;;; <param name="xfspPart">inbound xfServerPlus data instance</param>
		;;; <returns>Symphony data object based data</returns>
		public static method MoveToDataObject	,@<Structure_name>_Data
			in req xfspData						,@<Structure_name>
			endparams
		proc
			
			data returnData = new <Structure_name>_Data()

			<FIELD_LOOP>
			returnData.<FIELD_SQLNAME> = xfspData.<FIELD_SQLNAME>
			</FIELD_LOOP>
	
			mreturn returnData

		endmethod

	endclass

endnamespace

