//****************************************************************************
// WARNING: This code was generated by CodeGen. Any changes that you
//  		make to this code will be overwritten if the code is regenerated!
//
// Template author: Richard C. Morris, RCP Consultants
//
// Template Name:   Symphony Framework : SYMPHONY_SPA_MAINTLOGIC_V3_2.tpl
//
//***************************************************************************

//page wide types/variables

//field validation details
var mFieldDetails = Array();
var mDefaultBackground = null;

//Page on load event handler
function pageLoaded() {

	//get default settings
    mDefaultBackground = document.getElementById("txtBUYER_KEY").style.backgroundColor;
	
    //show the list selection view
    ToListSelectionView();

	var keySpecification = "";
	var separator = "";
    keySpecification += separator + "Buyer_key";
	separator = ",";
	
    LoadItemsFromServer("buyers", keySpecification, "name", null, null, 5);

	//sort out field level validation
	
    var control = null;
    control = new FieldControl('txtBUYER_KEY', true, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtCREATED_TIMESTAMP', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtMODIFIED_TIMESTAMP', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtNAME', true, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtADDRESS1', true, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtADDRESS2', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtADDRESS3', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtPOSTCODE', true, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtPHONE', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtMOBILE_PHONE', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtEMAIL', false, null, null);
	mFieldDetails.push(control);
    control = new FieldControl('txtFILLER', false, null, null);
	mFieldDetails.push(control);
}

//handler to display data when reloaded from the server
function DisplayData(itemToEdit) {
	var result = null;
    //put data into the fields
    document.getElementById("txtBUYER_KEY").value = itemToEdit.Buyer_key;
	document.getElementById("txtBUYER_KEY").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtCREATED_TIMESTAMP").value = itemToEdit.Created_timestamp;
	document.getElementById("txtCREATED_TIMESTAMP").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtMODIFIED_TIMESTAMP").value = itemToEdit.Modified_timestamp;
	document.getElementById("txtMODIFIED_TIMESTAMP").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtNAME").value = itemToEdit.Name;
	document.getElementById("txtNAME").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtADDRESS1").value = itemToEdit.Address1;
	document.getElementById("txtADDRESS1").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtADDRESS2").value = itemToEdit.Address2;
	document.getElementById("txtADDRESS2").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtADDRESS3").value = itemToEdit.Address3;
	document.getElementById("txtADDRESS3").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtPOSTCODE").value = itemToEdit.Postcode;
	document.getElementById("txtPOSTCODE").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtPHONE").value = itemToEdit.Phone;
	document.getElementById("txtPHONE").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtMOBILE_PHONE").value = itemToEdit.Mobile_phone;
	document.getElementById("txtMOBILE_PHONE").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtEMAIL").value = itemToEdit.Email;
	document.getElementById("txtEMAIL").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	
    document.getElementById("txtFILLER").value = itemToEdit.Filler;
	document.getElementById("txtFILLER").style.backgroundColor = mDefaultBackground;
	//if we have a change method, let's call it
	

    //disable key fields
    document.getElementById("txtBUYER_KEY").disabled = true;

    //focus the first page
    document.getElementById("txtNAME").focus(); 
    document.getElementById("txtNAME").select(); 
}

//handler to initialize the fields on the page
function InitializeData() {
    document.getElementById("txtBUYER_KEY").value = "";
    document.getElementById("txtCREATED_TIMESTAMP").value = "";
    document.getElementById("txtMODIFIED_TIMESTAMP").value = "";
    document.getElementById("txtNAME").value = "";
    document.getElementById("txtADDRESS1").value = "";
    document.getElementById("txtADDRESS2").value = "";
    document.getElementById("txtADDRESS3").value = "";
    document.getElementById("txtPOSTCODE").value = "";
    document.getElementById("txtPHONE").value = "";
    document.getElementById("txtMOBILE_PHONE").value = "";
    document.getElementById("txtEMAIL").value = "";
    document.getElementById("txtFILLER").value = "";

    ValidateResource(true);

    //disable key fields
    document.getElementById("txtBUYER_KEY").disabled = false;

    //focus the first page
    document.getElementById("txtBUYER_KEY").focus();
    document.getElementById("txtBUYER_KEY").select();
}

function SetFieldFocus(fieldSpec) {

	var infoText = "";
	switch (fieldSpec) {
		case "txtBUYER_KEY" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtCREATED_TIMESTAMP" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtMODIFIED_TIMESTAMP" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtNAME" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtADDRESS1" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtADDRESS2" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtADDRESS3" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtPOSTCODE" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtPHONE" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtMOBILE_PHONE" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtEMAIL" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
		case "txtFILLER" :
			infoText = "";
            document.getElementById("lblInfoBar").innerText = infoText.trim();
			break;
	}
}

//validate if field entry.
function ValidateResource(noChangeMethod) {

	validateBUYER_KEY(noChangeMethod);
	validateCREATED_TIMESTAMP(noChangeMethod);
	validateMODIFIED_TIMESTAMP(noChangeMethod);
	validateNAME(noChangeMethod);
	validateADDRESS1(noChangeMethod);
	validateADDRESS2(noChangeMethod);
	validateADDRESS3(noChangeMethod);
	validatePOSTCODE(noChangeMethod);
	validatePHONE(noChangeMethod);
	validateMOBILE_PHONE(noChangeMethod);
	validateEMAIL(noChangeMethod);
	validateFILLER(noChangeMethod);

}

function validateBUYER_KEY(noChangeMethod) {

	DataValueChangedValue("BUYER_KEY", null);
	infoText = "";
	document.getElementById("txtBUYER_KEY").title = infoText.trim();
	var fieldValue = document.getElementById("txtBUYER_KEY").value;

    if (fieldValue == null || fieldValue === "") {
		document.getElementById("txtBUYER_KEY").style.backgroundColor = mErrorBackground;
		document.getElementById("txtBUYER_KEY").title = "Non-blank/non-zero required.";
    }
    else {
        var regexTest = /^.{1,32}$/;
        var testResult = regexTest.test(fieldValue);
		if (testResult === true) {
			document.getElementById("txtBUYER_KEY").style.backgroundColor = mDefaultBackground;
		}
		else {
			document.getElementById("txtBUYER_KEY").style.backgroundColor = mErrorBackground;
			document.getElementById("txtBUYER_KEY").title = "Invalid value.";
		}
    }
}
function validateCREATED_TIMESTAMP(noChangeMethod) {

	DataValueChangedValue("CREATED_TIMESTAMP", null);
	infoText = "";
	document.getElementById("txtCREATED_TIMESTAMP").title = infoText.trim();
	var fieldValue = document.getElementById("txtCREATED_TIMESTAMP").value;

    var regexTest = /^[+]?[0]*[0-9]{0,19}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtCREATED_TIMESTAMP").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtCREATED_TIMESTAMP").style.backgroundColor = mErrorBackground;
		document.getElementById("txtCREATED_TIMESTAMP").title = "Invalid value.";
	}
}
function validateMODIFIED_TIMESTAMP(noChangeMethod) {

	DataValueChangedValue("MODIFIED_TIMESTAMP", null);
	infoText = "";
	document.getElementById("txtMODIFIED_TIMESTAMP").title = infoText.trim();
	var fieldValue = document.getElementById("txtMODIFIED_TIMESTAMP").value;

    var regexTest = /^[+]?[0]*[0-9]{0,19}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtMODIFIED_TIMESTAMP").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtMODIFIED_TIMESTAMP").style.backgroundColor = mErrorBackground;
		document.getElementById("txtMODIFIED_TIMESTAMP").title = "Invalid value.";
	}
}
function validateNAME(noChangeMethod) {

	DataValueChangedValue("NAME", null);
	infoText = "";
	document.getElementById("txtNAME").title = infoText.trim();
	var fieldValue = document.getElementById("txtNAME").value;

    if (fieldValue == null || fieldValue === "") {
		document.getElementById("txtNAME").style.backgroundColor = mErrorBackground;
		document.getElementById("txtNAME").title = "Non-blank/non-zero required.";
    }
    else {
        var regexTest = /^.{1,30}$/;
        var testResult = regexTest.test(fieldValue);
		if (testResult === true) {
			document.getElementById("txtNAME").style.backgroundColor = mDefaultBackground;
		}
		else {
			document.getElementById("txtNAME").style.backgroundColor = mErrorBackground;
			document.getElementById("txtNAME").title = "Invalid value.";
		}
    }
}
function validateADDRESS1(noChangeMethod) {

	DataValueChangedValue("ADDRESS1", null);
	infoText = "";
	document.getElementById("txtADDRESS1").title = infoText.trim();
	var fieldValue = document.getElementById("txtADDRESS1").value;

    if (fieldValue == null || fieldValue === "") {
		document.getElementById("txtADDRESS1").style.backgroundColor = mErrorBackground;
		document.getElementById("txtADDRESS1").title = "Non-blank/non-zero required.";
    }
    else {
        var regexTest = /^.{1,30}$/;
        var testResult = regexTest.test(fieldValue);
		if (testResult === true) {
			document.getElementById("txtADDRESS1").style.backgroundColor = mDefaultBackground;
		}
		else {
			document.getElementById("txtADDRESS1").style.backgroundColor = mErrorBackground;
			document.getElementById("txtADDRESS1").title = "Invalid value.";
		}
    }
}
function validateADDRESS2(noChangeMethod) {

	DataValueChangedValue("ADDRESS2", null);
	infoText = "";
	document.getElementById("txtADDRESS2").title = infoText.trim();
	var fieldValue = document.getElementById("txtADDRESS2").value;

    var regexTest = /^.{0,30}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtADDRESS2").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtADDRESS2").style.backgroundColor = mErrorBackground;
		document.getElementById("txtADDRESS2").title = "Invalid value.";
	}
}
function validateADDRESS3(noChangeMethod) {

	DataValueChangedValue("ADDRESS3", null);
	infoText = "";
	document.getElementById("txtADDRESS3").title = infoText.trim();
	var fieldValue = document.getElementById("txtADDRESS3").value;

    var regexTest = /^.{0,30}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtADDRESS3").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtADDRESS3").style.backgroundColor = mErrorBackground;
		document.getElementById("txtADDRESS3").title = "Invalid value.";
	}
}
function validatePOSTCODE(noChangeMethod) {

	DataValueChangedValue("POSTCODE", null);
	infoText = "";
	document.getElementById("txtPOSTCODE").title = infoText.trim();
	var fieldValue = document.getElementById("txtPOSTCODE").value;

    if (fieldValue == null || fieldValue === "") {
		document.getElementById("txtPOSTCODE").style.backgroundColor = mErrorBackground;
		document.getElementById("txtPOSTCODE").title = "Non-blank/non-zero required.";
    }
    else {
        var regexTest = /^.{1,10}$/;
        var testResult = regexTest.test(fieldValue);
		if (testResult === true) {
			document.getElementById("txtPOSTCODE").style.backgroundColor = mDefaultBackground;
		}
		else {
			document.getElementById("txtPOSTCODE").style.backgroundColor = mErrorBackground;
			document.getElementById("txtPOSTCODE").title = "Invalid value.";
		}
    }
}
function validatePHONE(noChangeMethod) {

	DataValueChangedValue("PHONE", null);
	infoText = "";
	document.getElementById("txtPHONE").title = infoText.trim();
	var fieldValue = document.getElementById("txtPHONE").value;

    var regexTest = /^.{0,20}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtPHONE").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtPHONE").style.backgroundColor = mErrorBackground;
		document.getElementById("txtPHONE").title = "Invalid value.";
	}
}
function validateMOBILE_PHONE(noChangeMethod) {

	DataValueChangedValue("MOBILE_PHONE", null);
	infoText = "";
	document.getElementById("txtMOBILE_PHONE").title = infoText.trim();
	var fieldValue = document.getElementById("txtMOBILE_PHONE").value;

    var regexTest = /^.{0,20}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtMOBILE_PHONE").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtMOBILE_PHONE").style.backgroundColor = mErrorBackground;
		document.getElementById("txtMOBILE_PHONE").title = "Invalid value.";
	}
}
function validateEMAIL(noChangeMethod) {

	DataValueChangedValue("EMAIL", null);
	infoText = "";
	document.getElementById("txtEMAIL").title = infoText.trim();
	var fieldValue = document.getElementById("txtEMAIL").value;

    var regexTest = /^.{0,50}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtEMAIL").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtEMAIL").style.backgroundColor = mErrorBackground;
		document.getElementById("txtEMAIL").title = "Invalid value.";
	}
}
function validateFILLER(noChangeMethod) {

	DataValueChangedValue("FILLER", null);
	infoText = "";
	document.getElementById("txtFILLER").title = infoText.trim();
	var fieldValue = document.getElementById("txtFILLER").value;

    var regexTest = /^.{0,500}$/;
    var testResult = regexTest.test(fieldValue);
	if (testResult === true) {
		document.getElementById("txtFILLER").style.backgroundColor = mDefaultBackground;
	}
	else {
		document.getElementById("txtFILLER").style.backgroundColor = mErrorBackground;
		document.getElementById("txtFILLER").title = "Invalid value.";
	}
}

function GetPageData(updateFieldList) {

    var pageDataObject = {};

	//first check we have a valid page
	var pageValid = true;
	var color = mDefaultBackground;
	color = document.getElementById("txtBUYER_KEY").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtCREATED_TIMESTAMP").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtMODIFIED_TIMESTAMP").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtNAME").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtADDRESS1").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtADDRESS2").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtADDRESS3").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtPOSTCODE").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtPHONE").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtMOBILE_PHONE").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtEMAIL").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}
	color = document.getElementById("txtFILLER").style.backgroundColor;
	if (color !== null && color !== mDefaultBackground) {
		pageValid = false;
	}

	if (pageValid === false) {
		return null;
	}

	if (updateFieldList === null) {
		pageDataObject["BUYER_KEY"] = document.getElementById("txtBUYER_KEY").value;
		pageDataObject["CREATED_TIMESTAMP"] = document.getElementById("txtCREATED_TIMESTAMP").value;
		pageDataObject["MODIFIED_TIMESTAMP"] = document.getElementById("txtMODIFIED_TIMESTAMP").value;
		pageDataObject["NAME"] = document.getElementById("txtNAME").value;
		pageDataObject["ADDRESS1"] = document.getElementById("txtADDRESS1").value;
		pageDataObject["ADDRESS2"] = document.getElementById("txtADDRESS2").value;
		pageDataObject["ADDRESS3"] = document.getElementById("txtADDRESS3").value;
		pageDataObject["POSTCODE"] = document.getElementById("txtPOSTCODE").value;
		pageDataObject["PHONE"] = document.getElementById("txtPHONE").value;
		pageDataObject["MOBILE_PHONE"] = document.getElementById("txtMOBILE_PHONE").value;
		pageDataObject["EMAIL"] = document.getElementById("txtEMAIL").value;
		pageDataObject["FILLER"] = document.getElementById("txtFILLER").value;
	}
	else
	{
		//always add the primary key
		pageDataObject["BUYER_KEY"] = document.getElementById("txtBUYER_KEY").value;

		//now add the requested fields
		for (var i = 0; i < updateFieldList.length; i++) {
			if (updateFieldList[i] !== "BUYER_KEY") {
				pageDataObject[updateFieldList[i]] = document.getElementById("txt" + updateFieldList[i]).value;
			}
		}
	}
	return pageDataObject;	
}


